import Head from "next/head";
import { useState } from "react";
import Button from "../components/Button";
import Layout from "../components/Layout";
import Table from '@material-ui/core/Table';
import TableBody from '@material-ui/core/TableBody';
import TableCell from '@material-ui/core/TableCell';
import TableContainer from '@material-ui/core/TableContainer';
import TableHead from '@material-ui/core/TableHead';
import TableRow from '@material-ui/core/TableRow';
import Paper from '@material-ui/core/Paper';


export default function Home() {
  const [inputData, setInputData] = useState();
  const [rowData, setRowData] = useState([])
  const handleClic = () => {
    fetch("http://localhost:8000/api/result", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ hash: inputData }),
    })
      .then((res) => res.json())
      .then((data) => {
        setRowData([data.student]);
      }
      );
  };
return (
  <Layout>
    <Head>
      <title>Certification app</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="m-auto w-2/5  flex flex-row">
      <input
        className="w-full border-solid p-2 border-2 border-black"
        type={"text"}
        placeholder={"Enter hash Id"}
        value={inputData}
        onChange={(e) => {
          setInputData(e.target.value);
        }}
      />
      <Button width="w-78" HandleCLick={handleClic}>
        Search
      </Button>
    </div>
    <div>
      {/* {"status":true,"student":{"name":"new try","rollNo":"32","result":"8.5","sem1":"8","sem2":"9","gender":"male","university":"something"}} */}
      <TableContainer component={Paper}>
        <Table sx={{ minWidth: 650 }} aria-label="simple table">
          <TableHead>
            <TableRow >
              <TableCell >Name</TableCell>
              <TableCell align="right">RollNo</TableCell>
              <TableCell align="right">Result</TableCell>
              <TableCell align="right">Sem1</TableCell>
              <TableCell align="right">Sem2</TableCell>
              <TableCell align="right">Gender</TableCell>
              <TableCell align="right">University</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {rowData && rowData.map((row) => (
              <TableRow
                key={row.name}
                sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
              >
                <TableCell component="th" scope="row">
                  {row.name}
                </TableCell>
                <TableCell align="right">{row.rollNo}</TableCell>
                <TableCell align="right">{row.result}</TableCell>
                <TableCell align="right">{row.sem1}</TableCell>
                <TableCell align="right">{row.sem2}</TableCell>
                <TableCell align="right">{row.gender}</TableCell>
                <TableCell align="right">{row.university}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </div>
  </Layout>
);
}
