import Head from "next/head";
import { useState } from "react";
import Button from "../components/Button";
import Layout from "../components/Layout";
// import Link from "next/link";

export default function Home() {
  const [inputData, setInputData] = useState();
  const handleClic = () => {
    // console.log("check1");
    console.log(inputData);
    fetch("http://localhost:8846/api/result", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ hash: inputData }),
    })
      .then((res) => res.json())
      .then((data) =>
        alert(
          `status: ${data.status}, student: ${JSON.stringify(data.student)}`
        )
      );
  };
  return (
    <Layout>
      <Head>
        <title>Certification app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="m-auto w-2/5  flex flex-row">
        <input
          className="w-full border-solid p-2 border-2 border-black"
          type={"text"}
          placeholder={"Enter hash Id"}
          value={inputData}
          onChange={(e) => {
            setInputData(e.target.value);
          }}
        />
        <Button width="w-78" HandleCLick={handleClic}>
          Search
        </Button>
      </div>
    </Layout>
  );
}
